[project]
name = "martyrologe"
version = "0.1.0"
description = "Données structurées pour un martyrologe."
author = "Timothé Watteau"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]
